# Generated by Django 6.0 on 2025-12-11 15:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "overview",
                    models.TextField(help_text="AI-generated summary of the plan."),
                ),
                ("total_steps", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weakness", "Address Weakness"),
                            ("strength", "Build on Strength"),
                            ("level_up", "Level Up Skill"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estimated_hours",
                    models.IntegerField(
                        help_text="Estimated hours to complete this step.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="tracker.roadmap",
                    ),
                ),
            ],
            options={
                "ordering": ["order_number"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("article", "Article"),
                            ("exercise", "Practice Exercise"),
                            ("ai_generated", "AI-Generated Content"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="External link (Youtube, Khan Academy, etc.)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "ai_content",
                    models.TextField(
                        blank=True, help_text="AI-generated study material.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roadmap_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="tracker.roadmapstep",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_description", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "roadmap_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="tracker.roadmapstep",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("maths", "Mathematics"),
                            ("english", "English"),
                            ("science", "Science"),
                            ("mandarin", "Mandarin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_spent",
                    models.FloatField(
                        help_text="Hours spent studying",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(24.0),
                        ],
                    ),
                ),
                ("session_date", models.DateField()),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about the session."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="tracker.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date"],
            },
        ),
        migrations.AddField(
            model_name="roadmap",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmaps",
                to="tracker.subject",
            ),
        ),
        migrations.CreateModel(
            name="ProgressAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("behind_schedule", "Behind Schedule"),
                            ("no_activity", "No Recent Activity"),
                            ("low_completion", "Low Completion Rate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="tracker.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strengths",
                    models.TextField(help_text="Areas where the student excels."),
                ),
                (
                    "weaknesses",
                    models.TextField(
                        help_text="Areas where the student is struggling."
                    ),
                ),
                (
                    "areas_to_improve",
                    models.TextField(help_text="Specific action items from teacher."),
                ),
                ("feedback_date", models.DateField()),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="tracker.subject",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Feedbacks",
                "ordering": ["-feedback_date"],
            },
        ),
        migrations.CreateModel(
            name="TermGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_level",
                    models.CharField(help_text="e.g., Grade 5, Level 3", max_length=50),
                ),
                (
                    "target_level",
                    models.CharField(help_text="e.g., Grade 7, Level 5", max_length=50),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("autumn_2025", "Autumn 2025"),
                            ("spring_2026", "Spring 2026"),
                            ("summer_2026", "Summer 2026"),
                        ],
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_goals",
                        to="tracker.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="roadmap",
            name="term_goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmaps",
                to="tracker.termgoal",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("parent", "Parent")],
                        max_length=10,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("year_group", models.IntegerField(blank=True, null=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_student",
                    models.ForeignKey(
                        blank=True,
                        help_text="For parents, link to the student they monitor.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
    ]
