# Generated by Django 6.0 on 2026-01-11 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_feedback_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="linked_student",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linked_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="For parents, link to the students they monitor.",
                related_name="parent_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Parent's contact phone number", max_length=20
            ),
        ),
    ]
