# Generated by Django 6.0 on 2026-01-15 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_remove_userprofile_linked_student_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progressalert",
            name="subject",
        ),
        migrations.AddField(
            model_name="progressalert",
            name="is_read",
            field=models.BooleanField(
                default=False, help_text="Whether parent has read the alert"
            ),
        ),
        migrations.AddField(
            model_name="progressalert",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent recieving the alert",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="progressalert",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progressalert",
            name="related_subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Related roadmap if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.subject",
            ),
        ),
        migrations.AddField(
            model_name="progressalert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("success", "Success"),
                ],
                default="info",
                help_text="Alert severity level",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="progressalert",
            name="title",
            field=models.CharField(
                blank=True, help_text="Alert title", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alert_frequency",
            field=models.CharField(
                choices=[
                    ("immediate", "Immediate"),
                    ("daily", "Daily Digest"),
                    ("weekly", "Weekly Digest"),
                ],
                default="daily",
                help_text="How often to send alert emails",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alert_goal_at_risk",
            field=models.BooleanField(
                default=True,
                help_text="Notify when goal deadline approaching with low progress",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alert_goal_at_risk_days",
            field=models.IntegerField(
                default=7, help_text="Days before deadline to send alert"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alert_low_activity",
            field=models.BooleanField(
                default=True, help_text="Notify when student hasn't studied in X days"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alert_low_activity_days",
            field=models.IntegerField(
                default=3, help_text="Days of inactivity before alert"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alert_milestones",
            field=models.BooleanField(
                default=True,
                help_text="Notify on milestone achievements (25%, 50%, 75%, 100%)",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alert_new_feedback",
            field=models.BooleanField(
                default=True, help_text="Notify when new teacher feedback is added"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alert_roadmap_completed",
            field=models.BooleanField(
                default=True, help_text="Notify when student completes a roadmap"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alert_streak_broken",
            field=models.BooleanField(
                default=True, help_text="Notify when study streak is broken"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_alert_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time alerts were sent to this parent",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="progressalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("low_activity", "Low Activity"),
                    ("goal_at_risk", "Goal at Risk"),
                    ("milestone_achieved", "Milestone Achieved"),
                    ("roadmap_completed", "Roadmap Completed"),
                    ("streak_broken", "Study Streak Broken"),
                    ("new_feedback", "New Teacher Feedback"),
                ],
                help_text="Type of alert",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="progressalert",
            name="is_sent",
            field=models.BooleanField(
                default=False, help_text="Whether email notification was sent"
            ),
        ),
        migrations.AlterField(
            model_name="progressalert",
            name="message",
            field=models.TextField(help_text="Detailed alert message"),
        ),
        migrations.AlterField(
            model_name="progressalert",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="Student this alert is about",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts_about",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="progressalert",
            index=models.Index(
                fields=["parent", "is_read"], name="tracker_pro_parent__bb1e96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progressalert",
            index=models.Index(
                fields=["created_at"], name="tracker_pro_created_3c114f_idx"
            ),
        ),
    ]
