# Generated by Django 6.0 on 2026-01-15 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_remove_progressalert_subject_progressalert_is_read_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="progressalert",
            name="parent",
            field=models.ForeignKey(
                help_text="Parent recieving the alert",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="progressalert",
            name="student",
            field=models.ForeignKey(
                help_text="Student this alert is about",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts_about",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="progressalert",
            name="title",
            field=models.CharField(help_text="Alert title", max_length=200),
        ),
    ]
