# Generated by Django 6.0 on 2026-01-17 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_progressalert_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressalert",
            name="related_roadmap",
            field=models.ForeignKey(
                blank=True,
                help_text="Related roadmap if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.roadmap",
            ),
        ),
        migrations.AlterField(
            model_name="progressalert",
            name="related_subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Related subject if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.subject",
            ),
        ),
    ]
